version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: order_dashboard_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adarsh123
      POSTGRES_DB: order_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: order_dashboard_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:adarsh123@db:5432/order_management
      - SECRET_KEY=38e3e4a9e525ad2a25ff0f11de8c3be3dfcb469123bde874e0d9b4db9a099aa5
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - PORT=8000
    depends_on:
      - db

volumes:
  postgres_data:
